### ISSUE TITLE
Log error on invalid angency host name

### ISSUE THREAD

**Issue by kwe712** [RWTH-ACS/clonemapy#2]
if an agency is created and the socket hostname doesn't conform to the intended pattern we get an index out of range. there is a check for this, but no consequence:

'''
temp = socket.gethostname()
logging.info("Agency: Starting agency " + temp)
hostname = temp.split("-")
self.hostname = hostname
if len(hostname) < 4:
    pass
masid = int(hostname[1])
'''

**Comment by s-daehling** [comment]
Thanks for the fix.
Pull request has been merged.
